spring.application.name=prueba
spring.datasource.url=jdbc:postgresql://localhost:5432/prueba
spring.datasource.username=postgres
spring.datasource.password=12345
server.port=8090
jwt.secret=mJ8vX2qL9rT4sW7yK3nP6dF1hG5cZ8bQ0aE2uI4oN6xR7tY9pS3wV5kJ1lH8gC
management.endpoints.web.exposure.include=health,info,metrics